medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
<<<<<<< HEAD
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') | as_number }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
=======
      host: "localhost"
      user: "postgres"
      password: "Blublah12@"
      port: 5432
      dbname: "medical_dw"
>>>>>>> f514872 (final and updated)
      schema: analytics
      threads: 4
