version: 2

models:
  - name: dim_channels
<<<<<<< HEAD
    description: "Channel dimension with aggregated stats."
=======
    description: "Channel dimension."
>>>>>>> f514872 (final and updated)
    columns:
      - name: channel_key
        description: "Surrogate key for channel."
        tests: [unique, not_null]
      - name: channel_name
<<<<<<< HEAD
        description: "Normalized channel name."
        tests: [unique, not_null]

  - name: dim_dates
    description: "Date dimension used for time-based analysis."
=======
        tests: [unique, not_null]

  - name: dim_dates
    description: "Date dimension."
>>>>>>> f514872 (final and updated)
    columns:
      - name: date_key
        tests: [unique, not_null]
      - name: full_date
        tests: [unique, not_null]

  - name: fct_messages
<<<<<<< HEAD
    description: "Fact table: one row per Telegram message."
=======
    description: "Fact table for telegram messages."
>>>>>>> f514872 (final and updated)
    columns:
      - name: message_id
        tests: [unique, not_null]
      - name: channel_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
<<<<<<< HEAD
=======
  - name: fct_image_detections
    description: "YOLO detections joined to messages for analysis."
    columns:
      - name: message_id
        tests: [not_null]
      - name: channel_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_channels')
                field: channel_key
      - name: date_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_dates')
                field: date_key
>>>>>>> f514872 (final and updated)
